### PR TITLE
[arm] bitwise manipulation instructions

### LINKED ISSUE #35: code-gen tests fail on macos
On Linux the assembler outputs `tzcnt` for all register types but on macos it outputs `tzcntw` (16bit), `tzcntl` (32bit), `tzcntq` (64bit), which makes the code-gen tests fail. 

The test script should "workaround this"~~, and we should also test macosx on travis to make sure it stays working.~~ EDIT: this is already being done.

### PR DESCRIPTION
**Pull request by gnzlbg**
This adds ARM's `rev`, `rbit`, `clz` and `cls` intrinsics. 

The `cls` intrinsic currently generates bad code due to an LLVM bug, I've filled issue #30 to track it.

Closes #35 .

### CODE REVIEW

**Comment by gnzlbg** [comment]
The code-gen tests for abm, bmi and bmi2 where failing so i've fixed those here.

**Comment by gnzlbg** [comment]
I don't have llc for arm installed, could somebody run:

```shell
llc -march=arm -mattr=help
llc -march=armv7 -mattr=help
llc -march=aarch64 -mattr=help
```

and post the output here? I don't know if its possible to use `#[target_feautre]` to force the generation of the arm intrinsics, but if that's possible, the answer will be there.

**Comment by gnzlbg** [comment]
@alexcrichton the tests are failing on travis, but they pass on my machine (MacOSX). Could we also test on Mac? The problem seems to be, that on linux the assembler emits, for example, `tzcnt`, but on MacOS it emits `tzcntw` (16bit), `tzcntl` (32bit), `tzcntq` (64bit), etc. Maybe the test plugin could handle those?

**Comment by gnzlbg** [comment]
The last commit truncates the instructions with the length of the expected instruction to omit the `w/l/q/etc` suffixes when present.

**Comment by BurntSushi** [comment]
@gnzlbg Thanks! So I think before we bring non-x86 intrinsics in, I'd really like to try to get CI setup to be able to test them. That's tracked in #13.

It also looks like the codegen tests are failing on Windows?

**Comment by gnzlbg** [comment]
> It also looks like the codegen tests are failing on Windows?

Were they working on windows before?

**Comment by gnzlbg** [comment]
> So I think before we bring non-x86 intrinsics in, I'd really like to try to get CI setup to be able to test them. That's tracked in #13.

I agree that CI for this is important. The now removed python script used to do CI for ARM by cross-compiling to arm archs and verifying the assembly. IIUC @alexcrichton will look into improving the assembly testing to do something like this. I wanted to look next into using `#[target_feature]` for these ARM features but can look into fixing #13 afterward. 

I think that for these three things (improving the code gen testing macros), using `#[target_feature]` for minor ARM features, and setting up full ARM CI, having some ARM code merged that we can actually test our approaches against will be very helpful.

**Comment by BurntSushi** [comment]
>  having some ARM code merged that we can actually test our approaches against will be very helpful.

Ah yeah good point! I can be sold on that. I think I would like to make sure the CI we do have is green though. I thought Windows was green at one point? Let's wait to hear from @alexcrichton (or I can look into it, but might be a bit).

**Comment by gnzlbg** [comment]
@alexcrichton this is the backtrace on appveyor:

```shell
---- x86::bmi::assert_instr__mm_tzcnt_u64 stdout ----
	thread 'x86::bmi::assert_instr__mm_tzcnt_u64' panicked at 'failed to find disassembly of stdsimd::x86::bmi::_tzcnt_u64', src\libcore\option.rs:839:4
stack backtrace:
---- x86::bmi::assert_instr__tzcnt_u32 stdout ----
	thread 'x86::bmi::assert_instr__tzcnt_u32' panicked at 'failed to get symbol of function pointer: 140698179428704', assert-instr\src\lib.rs:233:16
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
stack backtrace:
   0: std::sys_common::backtrace::_print
             at C:\projects\rust\src\libstd\sys_common\backtrace.rs:94
   1: std::panicking::default_hook::{{closure}}
             at C:\projects\rust\src\libstd\panicking.rs:380
   2: std::panicking::default_hook
             at C:\projects\rust\src\libstd\panicking.rs:391
   3: std::panicking::rust_panic_with_hook
             at C:\projects\rust\src\libstd\panicking.rs:577
   4: std::panicking::begin_panic<alloc::string::String>
             at C:\projects\rust\src\libstd\panicking.rs:538
   5: std::panicking::begin_panic_fmt
             at C:\projects\rust\src\libstd\panicking.rs:522
   6: assert_instr::assert
             at .\assert-instr\src\lib.rs:233
   7: test::{{impl}}::call_box<(),closure>
             at C:\projects\rust\src\libtest\lib.rs:141
   8: panic_unwind::__rust_maybe_catch_panic
             at C:\projects\rust\src\libpanic_unwind\lib.rs:99
---- x86::bmi::assert_instr__tzcnt_u64 stdout ----
```

It seems that `backtrace::resolve` is failing to find the symbol of a function pointer.

**Comment by gnzlbg** [comment]
@BurntSushi appveyor seems to be broken on master as well, I've enabled backtraces on appveyor for now, maybe we should do the same on travis.

File: assert-instr/src/lib.rs [hunk 1]
```diff
@@ -242,9 +242,14 @@ pub fn assert(fnptr: usize, expected: &str) {
     // Look for `expected` as the first part of any instruction in this
     // function, returning if we do indeed find it.
     for instr in function.instrs.iter() {
+        // Gets the first instruction, e.g. tzcntl in tzcntl %rax,%rax
         if let Some(part) = instr.parts.get(0) {
-            if part == expected {
-                return
+            // Truncates the instruction with the length of the expected
+            // instruction: tzcntl => tzcnt and compares that.
+            if let Some(part) = part.get(0..expected.len()) {
```
Comment (alexcrichton) [inline assert-instr/src/lib.rs]: I think this could be `part.starts_with(expected)`

(also thanksfor doing this!)

Comment (gnzlbg) [reply assert-instr/src/lib.rs]: Thanks! I looked a lot for something like that (or `contains`) in the docs but couldn't find it so thought it maybe wasn't part of `std`. I am learning a lot with your code reviews, thank you!

**Comment by alexcrichton** [comment]
Hm windows is indeed [previously green](https://ci.appveyor.com/project/rust-lang-libs/stdsimd/build/1.0.13)

**Comment by gnzlbg** [comment]
That is weird.

**Comment by alexcrichton** [comment]
Ok with the [most recent logs](https://ci.appveyor.com/project/rust-lang-libs/stdsimd/build/1.0.27) it looks like:

* `x86::bmi::assert_instr__mm_tzcnt_u32` - `backtrace` failed, but the symbol looks present
* `x86::bmi::assert_instr__tzcnt_u32` - symbol not actually present, I think it was folded into `_mm_tzcnt_u32`
* `x86::bmi::assert_instr__tzcnt_u64` - symbol not actually present, I think it was folded into `_mm_tzcnt_u64`
* `x86::sse2::assert_instr__mm_adds_epi16` - `backtrace` failed, but the symbol looks present

Testing more...

**Comment by alexcrichton** [comment]
@BurntSushi also yeah I'll work on ARM CI once we get this merged, it'll be helpful to have a few examples locally to test with

**Comment by alexcrichton** [comment]
Alright all green now! I'll add some comments then merge

File: .appveyor.yml [hunk 2]
```diff
@@ -1,4 +1,9 @@
 environment:
+  # We don't want to do identical comdat folding as it messes up the ability to
+  # generate lossless backtraces in some cases. This is enabled by rustc by
+  # default so pass a flag to disable it to ensure our tests work ok.
+  RUSTFLAGS: -Clink-args=/OPT:NOICF
```
Comment (gnzlbg) [inline .appveyor.yml]: I would have never thought of this.
